export const catchErrors = fn => (req, res, next) => {
    //High order fonction, permet de traiter automatiquement le catch sur une m√©thode
    return fn(req, res, next).catch(next);
}